import os
from building import *

# Add source code
src = Glob('*.c')

cwd = GetCurrentDir() # get current dir path

CPPPATH = [cwd]

group = DefineGroup('Applications', src, depend = [''] ,CPPPATH = CPPPATH)

Return('group')
