Import('RTT_ROOT')
Import('rtconfig')

import os
from building import *

# Add source code
src = Glob('*.c')

cwd = GetCurrentDir() # get current dir path

src += Glob(cwd + '/res/font/*.c')
src += Glob(cwd + '/res/image/*.c') 

CPPPATH = [cwd]

group = DefineGroup('Applications', src, depend = [''] ,CPPPATH = CPPPATH)

Return('group')
