CONFIG_BSP_USING_SPI1=y
# CONFIG_PA_USING_AW8155 is not set
CONFIG_RT_USING_DFS_ELMFAT=y
CONFIG_RT_DFS_ELM_CODE_PAGE=936
CONFIG_RT_USING_SPI_MSD=y
CONFIG_RT_USING_SPI_MSD_CS_PIN=y
CONFIG_RT_NAME_MAX=20
CONFIG_BSP_USING_FULL_ASSERT=y
CONFIG_AUDIO=y
CONFIG_AUDIO_LOCAL_MUSIC=y
CONFIG_PKG_USING_SGM41562B=y
CONFIG_PA_USING_NS4150B=y
CONFIG_PKG_USING_AUDIO_MANAGER_LIB=y
